name: RPM Build

env:
  name: collectd-selinux
  version: ${{ github.ref_name }}
  draft: true

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: build RPM package
      id: buildrpm7
      uses: carlospeon/buildrpm@centos7
      with:
        spec: contrib/${{ env.name }}.spec
        version: ${{ env.version }}
    # - name: copy rpms
    #   run: |
    #     cp ${{ steps.buildrpm7.outputs.rpms_path }}/noarch/*.el7.noarch.rpm .

    - name: build RPM package
      id: buildrpm8
      uses: carlospeon/buildrpm@rocky8
      with:
        spec: contrib/${{ env.name }}.spec
        version: ${{ env.version }}
    # - name: copy rpms
    #   run: |
    #     cp ${{ steps.buildrpm8.outputs.rpms_path }}/noarch/*.el8.noarch.rpm .

    - name: build RPM package
      id: buildrpm9
      uses: carlospeon/buildrpm@rocky9
      with:
        spec: contrib/${{ env.name }}.spec
        version: ${{ env.version }}
    # - name: copy rpms
    #   run: |
    #     cp ${{ steps.buildrpm9.outputs.rpms_path }}/noarch/*.el9.noarch.rpm .

    - uses: ncipollo/release-action@v1
      with:
        name: ${{ env.name }}-${{ env.version }}
        artifacts: "\
          ${{ steps.buildrpm7.outputs.rpms_path }}/noarch/*.el7.noarch.rpm,\
          ${{ steps.buildrpm8.outputs.rpms_path }}/noarch/*.el8.noarch.rpm,\
          ${{ steps.buildrpm9.outputs.rpms_path }}/noarch/*.el9.noarch.rpm"
        artifactContentType: application/x-rpm
        replacesArtifacts: true
        allowUpdates: true
        draft: ${{ env.draft }}
